### ISSUE TITLE
contributer

### ISSUE THREAD

**Issue by UmarFarooq-MP** [MarkMoretto/c-plus-plus#1]
Can i join you as contributer?

**Comment by MarkMoretto** [comment]
Yeah.  I mean, whatever I put up here that's public is open.

If you really want to collaborate on something, feel free to test and improve this rref package I'm working on.  https://pypi.org/project/rref/

**Comment by MarkMoretto** [comment]
Also, if you're interested in C++, there's Compiler Explorer for in-browser decomposition of scripts and whatnote.  Might be worth a look.

https://godbolt.org/

**Comment by UmarFarooq-MP** [comment]
I really appreciate your suggestions but i am more inclined towards c++ rather python and godbolt is a too big for a fresh cs graduate to absorb. Any suggestions from where should i start ?

**Comment by MarkMoretto** [comment]
Hmmm...I have some finished and unfinished projecteuler.com attempts for basic stuff:

Working folder:
https://github.com/MarkMoretto/project-euler/tree/master/cpp

Completed problems.  I like the .cxx extension, but .cpp also works:

https://github.com/MarkMoretto/project-euler/tree/master/complete



I bought the "Jumping into C++" book from Cprogramming.com.  It's pretty good, but the website has some solid stuff if you don't want to purchase it:

https://www.cprogramming.com/


This guy created BigInt for C++, but has a nice algos section:

https://github.com/faheel/Algos


And, here are some other github repos I've starred over the last year or so:

https://github.com/gibsjose/cpp-cheat-sheet

https://github.com/isocpp/CppCoreGuidelines

https://github.com/CppCon/CppConCodeOfConduct


Microsoft actually has some good stuff, too. Here's a page on the double type, but you could navigate through there and get some good examples:

https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=vs-2019

**Comment by UmarFarooq-MP** [comment]
This is so kind of you . Thank you very much .
